version: '3'
services:
  matches-service:
    build:
      context: .
      args:
        - DBHOST=arangodb
        - DBPW=$PW_STAG
    container_name: 'matches-service-stag'
    image: matches-service-stag
    ports:
    - 8000:8000
    links:
      - arangodb
    depends_on:
      - arangodb
  arangodb:
    container_name: 'matches-arangodb-stag'
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=$PW_STAG
    ports:
      - 8001:8529
    volumes:
      - /var/lib/iafoosball/matches-data/arango/stag:/var/lib/arangodb3