version: '2'
services:
  matches-service:
    build: './'
    ports:
      - 9000:4444
    volumes:
      - './api:$HOME/go/src/github.com/iafoosball/matches-service'
    links:
      - "arangodb"
    depends_on:
      - 'arangodb'

  arangodb:
    container_name: 'matches-arangodb'
    image: arangodb/arangodb:3.3.11
    ports:
      - 9001:8529
    environment:
    - ARANGO_ROOT_PASSWORD=iafoosball@matches for the win
    volumes:
    - $HOME/persistent/arangodb-matches-persistent:/var/lib/arangodb3

  swagger-ui:
    container_name: "matches-swagger"
    build: './swagger-ui/'
    ports:
      - 9002:8080

networks: 
  default:
    external:
      name: kong_iafoosball