version: '3'
services:
  matches-service:
    container_name: 'matches-service'
    build: './'
    ports:
      - 4444:4444
    volumes:
      - './api:$HOME/go/src/github.com/iafoosball/matches-service'
    links:
      - "arangodb"
#      - "arangodb:database"
    depends_on:
      - 'arangodb'
  arangodb:
    container_name: 'users-arangodb'
    image: arangodb/arangodb:3.3.11
    ports:
      - 8529:8529
    environment:
    - ARANGO_ROOT_PASSWORD=iafoosball for the win
    volumes:
    - /var/lib/arangodb-persistent:/var/lib/arangodb3

  swagger-ui:
    container_name: "swagger"
    build: './swagger-ui/'
    ports:
      - 2222:8080