version: '3'
services:
  matches-service:
    build:
      context: .
      args:
        - DBHOST=arangodb
        - DBPW=$PW_STAG
    container_name: 'matches-service-prod'
    image: matches-service-prod
    ports:
      - 9000:8000
  arangodb:
    container_name: 'matches-arangodb-prod'
    environment:
      - ARANGO_ROOT_PASSWORD=$PW_PROD
    ports:
      - 9001:8529
    volumes:
      - /var/lib/iafoosball/matches-data/arango/prod:/var/lib/arangodb3