version: '3'
services:
  matches-service:
    build: './'
    ports:
      - 8000:9000
    links:
      - arangodb
    depends_on:
      - arangodb

  arangodb:
    container_name: 'matches-arangodb'
    image: arangodb/arangodb:latest
    ports:
      - 8001:8529
    environment:
    - ARANGO_ROOT_PASSWORD=matches-password
    volumes:
    - /var/lib/iafoosball/arango/matches-data:/var/lib/arangodb3
