version: '3'
services:
  matches-service:
    build:
      context: .
    links:
      - arangodb
    depends_on:
      - arangodb

  arangodb:
    container_name: 'matches-arangodb'
    image: arangodb/arangodb:latest