version: '3'
services:
  matches-service:
    build: './'
    ports:
      - 9000
    volumes:
      - './api:$HOME/go/src/github.com/iafoosball/matches-service'
    links:
      - "arangodb"
#      - "arangodb:database"
    depends_on:
      - 'arangodb'
  arangodb:
    container_name: 'matches-arangodb'
    image: arangodb/arangodb:3.3.11
    ports:
      - 9004:8529
    environment:
    - ARANGO_ROOT_PASSWORD=iafoosball for the win
    volumes:
    - /var/lib/arangodb-persistent:/var/lib/arangodb3
  swagger-ui:
    container_name: "matches-swagger"
    build: './swagger-ui/'
    ports:
      - 9005:8080