version: '3'
services:
  matches-service:
    build:
      args:
        - DBHOST=matches-arangodb-stag
        - DBPW=$arangoPasswordStag
    container_name: 'matches-service-stag'
    ports:
    - 8000:8000
  arangodb:
    container_name: 'matches-arangodb-stag'
    ports:
      - 8001:8529
    volumes:
      - /var/lib/iafoosball/matches-data/arango/stag:/var/lib/arangodb3