version: '3'
services:
  matches-service:
    build: './'
    ports:
      - 9000:4444
    links:
      - arangodb
    depends_on:
      - arangodb

  arangodb:
    container_name: 'matches-arangodb'
    image: arangodb/arangodb:latest
    ports:
      - 9001:8529
    environment:
    - ARANGO_ROOT_PASSWORD=matches-password

    volumes:
    - /var/lib/arangodb-matches-persistent:/var/lib/arangodb3

#  swagger-ui:
#    container_name: "matches-swagger"
#    build: './swagger-ui/'
#    ports:
#      - 9002:8080