version: '3'
services:
  matches-service:
    build:
      context: .
      args:
        - DBHOST=arangodb
        - DBPW=$PW_PROD
    container_name: 'matches-prod'
    image: matches-prod
    ports:
      - 9000:8000
    links:
      - arangodb
    depends_on:
      - arangodb
  arangodb:
    container_name: 'matches-arangodb-prod'
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=$PW_PROD
    ports:
      - 9001:8529
    volumes:
      - /var/lib/iafoosball/matches-data/arango/prod:/var/lib/arangodb3