version: '3'
services:
  matches-service:
    container_name: 'matches-service-stag'
    ports:
    - 8000:8000
  arangodb:
    ports:
      - 8001:8529
    volumes:
      - /var/lib/iafoosball/arango/matches-data:/var/lib/arangodb3
