version: '3'
services:
  users-service:
    container_name: 'users-service'
    build: './'
    ports:
      - 4444:4444
    volumes:
      - './api:$HOME/go/src/github.com/iafoosball/users-service'
    links:
      - "arangodb"
#      - "arangodb:database"
    depends_on:
      - 'arangodb'
  arangodb:
    container_name: 'users-arangodb'
    image: arangodb/arangodb:3.3.11
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=joe
    volumes:
      - /tmp/arangodb:/var/lib/arangodb3